{
 "title": "Engine Details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "engine_id_manual", "label": "engine_id_manual", "query": "1,2,3,4,5,6,7,8,9,10" }
  ]
 },
 "panels": [
  {
   "title": "Details for Engine Number ${engine_id_manual}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Anomaly Score & Probability of Failure Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"engine_no\"] == \"${engine_id_manual}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\" or r[\"_field\"] == \"Probability of failure within 30 cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Last Anomaly Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"engine_no\"] == \"${engine_id_manual}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Last Prediction Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"engine_no\"] == \"${engine_id_manual}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Probability of failure within 30 cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Last Cycle",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"engine_no\"] == \"${engine_id_manual}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Completed cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Live Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"engine_no\"] == \"${engine_id_manual}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Top Anomaly & Predictive Features",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"engine_no\"] == \"${engine_id_manual}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  }
 ]
}