{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Engines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Engine ID\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Average # of Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\" or r[\"_field\"] == \"Engine ID\" or r[\"_field\"] == \"Probability of failure within 30 cycles\" or r[\"_field\"] == \"Completed cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Average Anomaly Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\" or r[\"_field\"] == \"Engine ID\" or r[\"_field\"] == \"Probability of failure within 30 cycles\" or r[\"_field\"] == \"Completed cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Average Prediction of Failure Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\" or r[\"_field\"] == \"Engine ID\" or r[\"_field\"] == \"Probability of failure within 30 cycles\" or r[\"_field\"] == \"Completed cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Engine Health Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\" or r[\"_field\"] == \"Engine ID\" or r[\"_field\"] == \"Probability of failure within 30 cycles\" or r[\"_field\"] == \"Completed cycles\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Top Failure Prediction Feature List (Score Over 50%)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Engine ID\" or r[\"_field\"] == \"Completed cycles\" or r[\"_field\"] == \"Probability of failure within 30 cycles\" or r[\"_field\"] == \"top_1_predictive_feature\" or r[\"_field\"] == \"top_2_predictive_feature\" or r[\"_field\"] == \"top_3_predictive_feature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Top Anomaly Feature List ( Anomaly Score Over 50%)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"antares\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly score\" or r[\"_field\"] == \"Engine ID\" or r[\"_field\"] == \"Completed cycles\" or r[\"_field\"] == \"anomaly_feature_1\" or r[\"_field\"] == \"anomaly_feature_2\" or r[\"_field\"] == \"anomaly_feature_3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}